### ISSUE TITLE
Open colorbox on an element of a group without clicking on the element

### ISSUE THREAD

**Issue by Seb33300** [jackmoore/colorbox#103]
Hello,

I need to open a specific element of a group in colorbox without using the "personal" link of this element.

example :
I have 3 grouped images we can see in the colorbox viewer by clicking on their link.
I have a preview image witch show a preview of their 3 images using "onmouseover" on links.

And I need to open colorbox by clicking the preview image on the image wich is previewed without duplicate them in the group.

Live example here :
http://seb33300.free.fr/colorbox/test2/example5/

If you click the preview image, the image previewed is duplicate in the group (witch is normal because i should trigger the event of the link).

**Comment by panablue** [comment]
The [FAQ](http://www.jacklmoore.com/colorbox/faq/#faq-click) example opens the first item in the group. Is it possible to specify an item # to start with?

**Comment by jackmoore** [comment]
@panablue That's what the call to [eq](https://api.jquery.com/eq/) is controlling.  The elements in the jQuery collection (`$("a[rel=gallery]"`) are zero-indexed, meaning that the first item is indexed at 0, the second is indexed at 1, and so on.  For example, to open the 5th item you would replace `eq(0)` with `eq(4)`.

**Comment by panablue** [comment]
Thank you so much for the quick reply.

That was my first thought but it doesn't have the desired effect in my particular scenario, maybe due to some existing jQuery for the clickable item in question, which hopefully I can weed out.

And thank you as always for the great Colorbox plugin.
