### ISSUE TITLE
Please add class support to options

### ISSUE THREAD

**Issue by cyberwombat** [jackmoore/colorbox#116]
I use cb to show images and videos which I want full width/height and ajax/text where I need padding. But I don;t have a way to set this without modifying my inserted content (not possible on my situation) - to be able to pass a css class as param would be wonderful so that I can style each cb accordingly.

**Comment by HongPong** [comment]
If anyone runs into this later, I had better luck with the following approach:
```
$.colorbox({inline: true,
                width: "80%",
                open: true,
                href: termsbox,
                speed: 200}).data('boxclass','TERMS');
```
and 
```
$(document).bind('cbox_complete', function(){
    console.log(jQuery.colorbox.element().data('boxclass'));
    var checkboxclass = jQuery.colorbox.element().data('boxclass');
    console.log('loading: ' + checkboxclass);
    $('#cboxContent').addClass(checkboxclass);
  });
```
Some clue to this should probably be on the main docs.
