### ISSUE TITLE
firefox fire 'isIE'

### ISSUE THREAD

**Issue by askovpen** [jackmoore/colorbox#385]
and get error:
TypeError: $box[0].style.removeAttribute is not a function

// v1.4.8 68539ba5c7a8d5ab9e99bd63038318d1437f03d3, firefox 19.0.2

**Comment by ceap80** [comment]
I'm seeing this error on Chrome "Version 60.0.3107.4 (Official Build) dev (64-bit)" on an Ubuntu 16.04 machine.

But I don't get the error on "Chrome Version 58.0.3029.110 (64-bit)" on the same machine.

I'm using colorbox version 1.6.3 I have not tested yet version 1.6.4 but a didn't find changes around the $box[0].style.removeAttribute line, it seems the same code as version 1.6.3

jQuery version is "v1.12.4" in both cases.

**Comment by jackmoore** [comment]
@ceap80 I think your issue is probably unrelated to this closed ticket. Do you mind creating a new ticket and providing a demo with the minimum needed to reproduce your problem?

**Comment by jackmoore** [comment]
@ceap80 I'm not too concerned about issues in non-stable browser releases.
