### ISSUE TITLE
Colorbox + jQuery UI Dialog

### ISSUE THREAD

**Issue by ghost** [jackmoore/colorbox#389]
Hi, I am using colorbox (1.4.10) with jQuery UI Dialog (1.10.2) with jQuery 1.9.1.

When an UI Dialog form is opened upon a colorbox,
the input text field on the UI Dialog can not be focused because 'trapFocus' seems to interrupt a focus event.

Is this wrong usage? Thanks.

**Comment by pavannie** [comment]
Hi, 

I have the similar problem. In my colorbox I have a button, on click of the button I am opening jqueryUI dialog. However, the dialog is getting placed behind the colorbox. I tried trapFocus as false but it dint help. Could some one help with this?

**Comment by Globulopolis** [comment]
@pavannie I think it's because z-index value in colorbox set to 9999, but in the jqueryUI dialog this value is 100 and 101.
Small crutch is it to use different z-index for colorbox.
See reduced example at http://jsfiddle.net/pg77fpL0/

**Comment by pavannie** [comment]
@Globulopolis  Thank you, it worked !!!
