### ISSUE TITLE
[wish] 'next', 'previous' and 'close' button absolute position on screen 

### ISSUE THREAD

**Issue by Deevad** [jackmoore/colorbox#413]
Hi, superb script, thanks. 

On my gallery ( artworks of various aspect ratio ) the 'next' and 'previous' buttons constantly change position after pushing 'next' or 'previous'  ( http://www.davidrevoy.com ). 

I'm updating it now with the new Colorbox version on local host, and I was looking for a way to have those buttons positioning in a absolute fashion on screen, but this is out of my hacking capacity. css magic? js magic ?  :-)  Thanks in advance if you can help me. 

other ref : 
http://dimsemenov.com/plugins/magnific-popup/
http://jenniferahrens.com/

mockup : 
![2013-04-20_screenshot_01](https://f.cloud.github.com/assets/4021867/405076/ba51195c-a9af-11e2-9081-8b6741212b53.jpg)

**Comment by joaogarin** [comment]
Hello,

is this already supported? When adding fixed position the element does not get displayed becaues there is an overflow:hidden; on top elements. If I remove that overflow:hidden then there is a huge animation blank when moving between images =/

**Comment by bragovo** [comment]
position: fixed;
Not working anymore. http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue
Working in FF, but not in WebKit — https://code.google.com/p/chromium/issues/detail?id=20574

It's a little problem =)
