### ISSUE TITLE
Colorbox and Flexslider, the colorbox next and previous are the interacting with flexslider and causing strange things

### ISSUE THREAD

**Issue by carasmo** [jackmoore/colorbox#417]
Hello,

Colorbox is fantastic and it's working fine, but when I click next or previous in the overlay the Flexslider below shifts to the left or the right in unexpected and strange ways and it won't correct itself, it adds about 50% to the slide in IOS and 20px in Firefox.  Is there anything I can do to correct this?

Thanks!

**Comment by Takaya213** [comment]
Also having this issue with Flexslider and Colorbox.

**Comment by oleprinds** [comment]
For future reference.
The problems are caused by the colorbox setting 'returnFocus', which tries to return focus to the flexslider (or Carousel) image. Setting returnFocus to false, solves the issue.
