### ISSUE TITLE
please make colorbox AMD compatible

### ISSUE THREAD

**Issue by szepeviktor** [jackmoore/colorbox#427]
please make colorbox AMD compatible as jQuery is

like:
https://github.com/amdjs/amdjs-api/wiki/AMD#api-specification

Thank you!

**Comment by ericnewton76** [comment]
ding.  its 2018 and everything is AMD

**Comment by szepeviktor** [comment]
> ding. its 2018 and everything is AMD

ding. its 2018 and everything is ES6 modules!
