### ISSUE TITLE
colorbox keeps on flickering in IOS (IPAD)

### ISSUE THREAD

**Issue by wilson12** [jackmoore/colorbox#475]
colorbox flickers/blinks a lot before as it opens in IOS(IPAD) safari browser am i missing any parameter.
$.colorbox({href:"<?php echo $base_url ?>test/getMediaInfo", 
           data:{id: $(this).attr('mid')}, 
            title: 'Media Details',
           opacity :0,
                onComplete:function(){$.colorbox.resize()},
                onClosed:function(){}
          });
It feels like it keeps on resizing .I have tried the code without the above  $.colorbox.resize() but still it keeps on flickering.
 its running great in desktop browsers and in safari desktop also .
The only problem is in Ipad ..
Gave the colorbox height and width still it keeps on flickering.
colorbox :- jQuery ColorBox v1.3.31 
jQuery :-  v1.8.3

**Comment by andrew-pardue** [comment]
Just for future people who may stumble upon this.  Older iOS flickering issues with colorbox, for me at least, were resolved by setting colorbox to be relative to the document (rather than fixed in the users viewport)
