### ISSUE TITLE
jQuery UI DatePicker bug when called from colorbox using IE

### ISSUE THREAD

**Issue by davlinski** [jackmoore/colorbox#477]
We have a form that is being displayed as an inline HTML colorbox. One of the form fields is a DatePicker (implemented using jQuery UI). When we run this in Internet Explorer versions 9+ the month and year drop-downs don't work properly. In order to access these values the user has to double-click the control. In Chrome and IE v7-8 it works as expected; the user can simply select the drop-down and select a value.

I've tried this using other lightbox libraries and it works as expected.

Any idea how we might get this to work?

**Comment by rjm-ms** [comment]
This saved my day! Thanks
