### ISSUE TITLE
Open first changed colorbox after onClosed event of second.

### ISSUE THREAD

**Issue by sergeyvershinin** [jackmoore/colorbox#478]
Hi, there is my example:
http://dev2.audace.ru/index.php?option=com_vvmag&view=good&id=19&catid=21&Itemid=126

I open first colorbox with order form ("Купить" button, http://take.ms/NJJ66), make some changes in form, then open second colorbox from inside of first (http://take.ms/YJPID). Then i want the first colorbox will be shown again with my changes after second is closed. Is it possible? Thank you for greatful plugin!

**Comment by pavannie** [comment]
Can I create two colorboxes? i,e first colorbox default and with on click of button present in first colorbox should open another colorbox ?

**Comment by jackmoore** [comment]
Sorry, again this is something that isn't supported (and it would not be a minor change to support it).
