### ISSUE TITLE
Redundancy on checking if colorbox being applied to empty collection 

### ISSUE THREAD

**Issue by alexeiTruhin** [jackmoore/colorbox#685]
Line 572:

		if ($.isFunction($obj)) { // assume a call to $.colorbox
			$obj = $('<a/>');
			options.open = true;
		} else if (!$obj[0]) { // colorbox being applied to empty collection
			return $obj;
		}

		if (!$obj[0]) { // colorbox being applied to empty collection
			return $obj;
		}

**Comment by aik099** [comment]
I saw you've made a couple of PR lately. Does any of them fix what you've reported here? If so, then please mention this task in PR description that fixes it.

**Comment by jackmoore** [comment]
Thanks, merged your pull request to remove the duplicated lines.
