### ISSUE TITLE
Youtube embed - Autoplay is not working in mobile and tablet (iphone / ipad)

### ISSUE THREAD

**Issue by Sharon831** [jackmoore/colorbox#689]
Hello,

I am using colorbox in my magento shop to show product videos, it works perfect on my computer that the autoplay is functioning, but not at all in mobile (iPhone 5) and tablet (iPad-mini). Also in the script, I set the maxWidth and maxHeight of the overlay window and a fixed width and height in the youtube embed parameter, but in the mobile version, the screen of the video got cut off. 

Here is my code:
``` 
<a href="javascript:void jQuery.colorbox({html:'<iframe width=710 height=520 src=http://www.youtube.com/embed/QJmQGE53rdw?HD=1;autoplay=1;rel=0;showinfo=0;controls=0; frameborder=0 allowfullscreen></iframe>',maxWidth:'95%', maxHeight:'95%', })"><img src="homepage/promotion_banners/video-thumb_frontpage.jpg"" alt="" /></a>

 ```

How can I fix these issues - autoplay the video in mobile and tablet when the image is clicked and size of the video screen fit into the overlay window.

Thanks
Sharon

**Comment by jackmoore** [comment]
If you just add the iframe to your page, without using Colorbox, does it autoplay as you expect?

Some browsers do not like having an iframe moved around in the DOM after the src has been set, which Colorbox does do for any HTML it's passed in as part of measuring it's dimensions.  When Colorbox creates an iframe itself (by using the iframe property), it waits until after the iframe is in it's final location in the DOM before setting the src.  I would suggest waiting until the onComplete event fires to set the iframe's src, to see if that resolves the issue.  For example:
```
jQuery.colorbox({
	html:'<iframe id="example" width=710 height=520 frameborder=0 allowfullscreen></iframe>',
	maxWidth:'95%',
	maxHeight:'95%',
	onComplete: function(){
		jQuery('#example')[0].src = "http://www.youtube.com/embed/QJmQGE53rdw?HD=1;autoplay=1;rel=0;showinfo=0;controls=0;";
	}});
```

**Comment by aik099** [comment]
Or maybe you can read contents of ColorBox via AJAX request (ColorBox already supports that).

**Comment by Sharon831** [comment]
Hello,
Thanks for a quick response.
I tried to use the script you gave it to me, then it turns to be playing the video when the page is onloading. Please check: http://au.reenbergs.com/

While the video screen still cut half in the overlay box. (but the video doesn't pop up right after the page is loaded like on desktop).

Here is my code:
```
<a href="javascript:void jQuery.colorbox();"><img src="{{media url="wysiwyg/reenbergs/homepage/promotion_banners/video-thumb_frontpage.jpg"}}" alt="" /></a>
<script>
jQuery.colorbox({
    html:'<iframe id="example" width=710 height=520 frameborder=0 allowfullscreen></iframe>',
    maxWidth:'95%',
    maxHeight:'95%',
    onComplete: function(){
        jQuery('#example')[0].src = "http://www.youtube.com/embed/QJmQGE53rdw?HD=1;autoplay=1;rel=0;showinfo=0;controls=0;";
    }});
</script>
```

**Comment by jackmoore** [comment]
It was just an example, not intended to be a copy-paste-solution to your problem. But is sounds like it resolved your playback issue?  For the exact HTML you are using, I don't see any reason not to just go ahead and use the iframe property that Colorbox provides.  Here is a another example that you should be able to copy-paste:
```
<a class="iframed-video" href="http://www.youtube.com/embed/QJmQGE53rdw?HD=1;autoplay=1;rel=0;showinfo=0;controls=0;"><img src="{{media url="wysiwyg/reenbergs/homepage/promotion_banners/video-thumb_frontpage.jpg"}}" alt="" /></a>
<script>
jQuery('.iframed-video').colorbox({
	width: 710,
	height: 520,
	maxWidth: '95%',
	maxHeight: '95%',
	iframe: true,
});
</script>
```

**Comment by swiftini** [comment]
Autoplay is not supported in iphone and Android devices

**Comment by neoplomero** [comment]
swiftini your face is just perfect for your answer
