### ISSUE TITLE
What to do when iframe isn´t working: X-Frame-Options

### ISSUE THREAD

**Issue by emtiey** [jackmoore/colorbox#706]
My iframes are empty, because sites like google uses X-Frame-Options.

My idea was to use onclick="window.open

But this seems not to work with colorbox.

**Comment by jackmoore** [comment]
You can't iframe a website that disallows iframing, so I would say don't use Colorbox for those links.

**Comment by emtiey** [comment]
Isn´t it possible to combine javascript popup (onclick=widow.open) with your plugin?

That would output the same as iframe, i think. Couldn´t find anything like that in Faq section.

**Comment by jackmoore** [comment]
I don't understand how you would be using them together.  Colorbox and window.open are unrelated things (Colorbox operates within the current window, window.open creates a new window).
