### ISSUE TITLE
Responsive Youtube iframe

### ISSUE THREAD

**Issue by fourroses666** [jackmoore/colorbox#717]
Hi, I use the following code:
``$(".youtube").colorbox({iframe:true, innerWidth:640, innerHeight:390});``

How can I get the popup responsive. 
Can't find anything about this.

**Comment by jackmoore** [comment]
This isn't a comprehensive answer, but you could use percent-based measurements:
```
$(".youtube").colorbox({iframe:true, width:'90%', height:'90%'});
```

**Comment by fourroses666** [comment]
I will try to solve it with css, else I need to use some other script :(

maybe its possible to add responsive stuff in the code?
like adding breakingpoints for responsive: < 640 - innerwidth 480, innerheight 300 | < 480 - innerwidth 320, innerheight 220 or something like that.
