### ISSUE TITLE
Event Listener cbox_complete Not Firing 

### ISSUE THREAD

**Issue by svoltmer** [jackmoore/colorbox#731]
I am trying to use the event listener "cbox_complete" to adjust the height of several elements in colorbox using this code below, but the event never fires? Is there something wrong with my syntax?

$(document).bind('cbox_complete', function(){
    var cboxTitleHeight = $('#cboxTitle').height();
    var cboxContentHeight = $('#cboxContent').height();
    var cboxWrapperHeight = $('#cboxWrapper').height();
    var colorboxHeight = $('#colorbox').height();

    $('#cboxMiddleLeft, #cboxMiddleRight, #cboxContent').css('height', (cboxContentHeight + cboxTitleHeight) + 'px');
    $('#cboxWrapper').css('height', (cboxWrapperHeight + cboxTitleHeight) + 'px');
    $('#colorbox').css('height', (colorboxHeight + cboxTitleHeight) + 'px' );
});

**Comment by jackmoore** [comment]
Worked fine for me.

**Comment by svoltmer** [comment]
Hmm, maybe it's where it is located. We are using a content management system that pulls in the colorbox.js as a on-page instance of code called a "macro". I've tried placeing the listener on the header of the page and within the macro containing the colorbox.js and it never seems to apply the css height changes. Any suggestions?

**Comment by svoltmer** [comment]
I can see the event listener using the dev tools in Chrome, but I've now tried "cbox_load" as well, with no results either.

**Comment by jackmoore** [comment]
Sorry, I do not know.  You should provide a link demonstrating the problem, but I bet if you try to reduce the problem to a simple demo you'll discover what the issue is. I feel confident that the event works as expected, and that the issue is something specific to your implementation. 

My guess is that you have multiple instances of jQuery running on the same page.  I'm not positive about this, but I believe if you have jQuery multiple times on a single page, one instance will not be able to detect *custom events* (like `cbox_complete`) generated by some other instance.

**Comment by svoltmer** [comment]
Click on the first photo on the content of this page to start the slideshow. http://edit-wwwprep.rose-hulman.edu/admissions-financial-aid/early-planning/operation-catapult.aspx
Right now I have cboxTitle styled to cover the bottom of the image, but if this javascript would work, it would dynamacally add the additional height that I need to show all of the photo.

I would appreciate it if you could take a look at the page an give me some idea of what is going on. Thanks!

**Comment by jackmoore** [comment]
I opened your page and copy-pasted the code from your first post into the console.  It seemed to work fine.  However, as I guessed, you do have multiple instances of jQuery running on that page.  Also, I did not see the code that you were asking about in any of the scripts.  Are you sure the code you are trying to run is being loaded by the page?

**Comment by svoltmer** [comment]
I had it loading within the macro, but for the sake of the argument, I put it in the header and I still don't see it working. Now, if like you, I paste it into the console it works fine. I don't understand why though.

**Comment by svoltmer** [comment]
I removed the other instance of jquery that was loading as well, and it still doesn't function.
