### ISSUE TITLE
improper case of iframe attribute line 118

### ISSUE THREAD

**Issue by tomagnew** [jackmoore/colorbox#737]
Line 118 of jquery-colorbox.js reads:

iframe.allowFullScreen = true;  (should read iframe.allowFullscreen = true)

This improper attribute causes YouTube fullscreen buttons not to show.

Thanks!

**Comment by jackmoore** [comment]
So it is, thanks!

**Comment by tomagnew** [comment]
Thank you for this awesome plug-in and your continued support of it!
