### ISSUE TITLE
JS error when using initialWidth/initialHeight options on IE8

### ISSUE THREAD

**Issue by jon301** [jackmoore/colorbox#741]
Hi,
I believe a regression has been introduced in release v1.5.6 : the plugin throws an error when using initialWidth or initialHeight options on IE8

```
Version 1.5.6 - 2014/4/4
Applied maxWidth and maxHeight to the initialWidth and initialHeight. Fixes #391
```

Here are some URL examples : 
v1.5.5, **working** on IE8
http://output.jsbin.com/mawucu

v1.5.6, **not working** on IE8
http://output.jsbin.com/qerose 

The bug is still here on the current version (v1.6.2)

Thank you for your help

**Comment by jackmoore** [comment]
I believe that should fix it.  Thanks for doing so much of the leg work on this.

**Comment by jon301** [comment]
It works, thanks for your very fast answer !
