### ISSUE TITLE
Question : transition between colorboxes

### ISSUE THREAD

**Issue by jon301** [jackmoore/colorbox#742]
Hi,

It is more a question than an issue :

In the following example, I make a transition between 2 colorboxes using the "html" attribute.
Is it possible to show the content of the 2nd colorbox instantly without the loading GIF and the white empty box glitch ? (I tried to apply a "display: none" on the .cboxLoadingOverlay element but it didn't work)

http://jsbin.com/buwicu

Thank you for your help !

**Comment by jackmoore** [comment]
If you set the transition speed to 0, then there wouldn't be a loading animation.  Otherwise it's something you'd have to modify the plugin to support.

**Comment by jon301** [comment]
Thanks !
