### ISSUE TITLE
Can't Open Colorbox From Within a bxSlider Slide

### ISSUE THREAD

**Issue by svoltmer** [jackmoore/colorbox#746]
I have a slide within a bxSlider, that should trigger the opening of a colorbox slideshow. It opens a colorbox, but never loads the slideshow. here is call to the colorbox() within the bxSlider:

$('.isSlideshow').colorbox({rel:'slideGroup'});

Where the class "isSlideshow" is on the link within the bxSlider slide and of course the rel:'slideGroup' is on the unordered list containing the slides with the rel of slideGroup. Never loads the slides.

**Comment by svoltmer** [comment]
Wow, so easy! I just had to attach an event handler to the slide in the bxslider and using the on() method call .colorbox in a function like this:

$('.slide').on('click','a.isSlideshow', function() {
        $('a.slideGroup').colorbox({rel:'slideGroup1', open:true});
   });

**Comment by jackmoore** [comment]
👍

**Comment by svoltmer** [comment]
Jack,
Quick question regarding my use of the event handler. The way I called colorbox works great, but if I try to add an additional hyperlink in the caption for the slide in the same way, it creates a duplicate colorbox group and then the total number of slides in the colorbox is doubled. What is the proper way to make a second call to the same slideGroup? Thanks for any suggestions Jack.
