### ISSUE TITLE
Need to escape for colon for inline hrefs

### ISSUE THREAD

**Issue by bcinarli** [jackmoore/colorbox#749]
Sometimes, inline elements IDs have colons. For selecting them with jQuery, they need to have escaped.

Currently, Colorbox fails to load

```html
<div id="#hidden:content">Hidden</div>
```
```js
$.colorbox({
    inline: true,
    href: "#hidden:content"
})
```

For fixing it,

```js
var escapeSelector = function(selector) {
        var is_ID = selector.charAt(0) === '#',
            re = /([ !"#$%&'()*+,.\/:;<=>?@[\\\]^`{|}~])/g;

        return is_ID ? '#' + selector.substring(1).replace(re, '\\$1') : selector;
    };

// in the Colorbox, I think the right place is 
// https://github.com/jackmoore/colorbox/blob/master/jquery.colorbox.js#L953
...
var $target = $(escapeSelector(href));
```

**Comment by jackmoore** [comment]
I don't think this should be Colorbox's responsibility... you should pass it selectors that are valid to jQuery or document.querySelector.  I would change the selector, but if you must keep it that way, escape your selector before giving it to Colorbox.

**Comment by bcinarli** [comment]
Ok, I did a wrapper for Colorbox and escaping the selector before initializing Colorbox. Note that, Below samples are not working with colorbox.

```html
<a href="#test:block" class="colorbox">Inline Anchor</a>
<a href="#test\\:block" class="colorbox">Inline Anchor</a>
```

```js
$(".colorbox").colorbox({inline:true});
```
