### ISSUE TITLE
Blocked loading mixed active on https website for youtube video

### ISSUE THREAD

**Issue by kressly** [jackmoore/colorbox#755]
Hello
I am trying to use colorbox for youtube video but this is what on my https website. Can you please help me out ? This is a bit urgent.  Thanks

**Comment by jackmoore** [comment]
You should be able to link to https://youtube.com instead of http://youtube.com, or use the protocol-relative path.  For example:
```
<a href="//www.youtube.com/embed/VOJyrQa_WR4">Example</a>
```

**Comment by kressly** [comment]
Hello
I did that yet still it is not showing the video. In the Href i first use https but it did not so i removed the https:// and replaced it with // but it is still not working.
Please visit this page and tell me why is it not working

https://holyunions.com/pages-all.php?id=14

I now get the followiing error
Load denied by X-Frame-Options: https://www.youtube.com/watch?v=jmtO65_oUtQ&feature=youtu.be does not permit cross-origin framing.

**Comment by binaryannie** [comment]
You should use the embed link like so : 

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/jmtO65_oUtQ" frameborder="0" allowfullscreen></iframe>
```

You can get this link on the share part of the video by clicking on the embed "tab".

**Comment by kressly** [comment]
@binaryannie  thks
