### ISSUE TITLE
'only-html'  method not working 

### ISSUE THREAD

**Issue by palashc2011** [jackmoore/colorbox#756]
```
$.colorbox({html:"<h1>Welcome</h1>"}); 
```

this gives me this error: 'Cannot read property 'indexOf' of undefined'

**Comment by jackmoore** [comment]
That works fine for me.

**Comment by palashc2011** [comment]
Apologies Sir.... It was a local edit that was blocking it.. Thank you for
considering and for this awesome plugin.
