### ISSUE TITLE
SVG images aren't working

### ISSUE THREAD

**Issue by a4jp-com** [jackmoore/colorbox#761]
None of my SVG images are working. Can you update Colorbox so it works with SVG files?

**Comment by jackmoore** [comment]
> None of my SVG images are working.

Then provide a demonstration.  SVG works fine in my testing.

**Comment by jackmoore** [comment]
My guess is that Colorbox's regex can't match the src you are using for your images.  Colorbox expects src to images to end with a known image file extension, for example: `https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg`

But you don't have to change your src, just set Colorbox's photo property to true to by-pass the regex matching: http://www.jacklmoore.com/colorbox/#setting-photo
