### ISSUE TITLE
Black background occurs when loading ajax html

### ISSUE THREAD

**Issue by ArsenePadthai** [jackmoore/colorbox#764]
Hi, Jack,
I meet a problem when I try to use colorbox to load a ajax html. It seems the box has a black background for about 1 second before my html is entirely loaded. Here is the jsfiddle. https://jsfiddle.net/63bk7Lzq/1/ . I am wondering if someone ever meet the same problem.  Thank you so much.

**Comment by jackmoore** [comment]
It's from this line in the CSS:
```
#cboxLoadingOverlay{background:#000;}
```

Just change it to whatever you want it to be.
