### ISSUE TITLE
Not work properly with the image size: 1350x2127

### ISSUE THREAD

**Issue by k008** [jackmoore/colorbox#770]
Not work properly with the image size: **1350x2127**.
Writes error: This image failed to load

It can do to open in a new tab without script if an error?

Use: **jquery.colorbox.js**

**Comment by jackmoore** [comment]
Sorry, need a demo.  I doubt it has anything to do with your image size.

**Comment by k008** [comment]
This script is used in the theme: Esplanade
on the CMS: wordpress.

**Comment by k008** [comment]
Why closed a request?

**Comment by jackmoore** [comment]
Because there is no actionable information, and I'm fairly confident whatever problem you are having is unrelated to what you have described so far.

**Comment by k008** [comment]
So you can display the page with the problem?

**Comment by svenbluege** [comment]
@k008 Please check your servers error log. This kind of issue occurs usually if the server can't process your image. Most of the time there is not enough memory to process images that large. Colorbox will get a HTTP 500 result which is hard to transform into an image. You can also use your browsers developer tools to make sure the images is coming correctly from the server.

**Comment by k008** [comment]
Strangely, before creating a request, I tested on 3 different servers, and as the situation did not work.
Now I check on the ground and there are no problems.

Play around more, thank you.
