### ISSUE TITLE
It doesn't work with Jquery 1.4

### ISSUE THREAD

**Issue by vascious** [jackmoore/colorbox#774]
Hi,

I have followed all your instructions and it says on your site that the colorbox is jquery compatible with version 1.4 but it doesn't seem to be.  Can you clarify?  when I use it all it does is open the image/files/webpages into a new window.

Thanks,
Nolan

**Comment by jackmoore** [comment]
Are you using jQuery 1.4.4?  I'm only interested in supporting the last point release, it's not really feasible or reasonable to support versions with known issues.

**Comment by vascious** [comment]
I am not sure.  my file says 1.4.min
