### ISSUE TITLE
Loading images via ajax and then again initialize colorbox on those

### ISSUE THREAD

**Issue by yasharma** [jackmoore/colorbox#775]
I have an album of images from those album first image displayed to user:  following **index.html**
```html
<p><a class='ajax' href="../content/ajax.html" >image 1</a></p>
<script>
    $(".ajax").colorbox();
</script>
```
Following is: **ajax.html**
```html
<p><a class="groupAjax" href="../content/ohoopee1.jpg" title="Me and my grandfather on the Ohoopee."><img src="../content/ohoopee1.jpg"></a></p>
<p><a class="groupAjax" href="../content/ohoopee2.jpg" title="On the Ohoopee as a child"><img src="../content/ohoopee2.jpg"></a></p>
<p><a class="groupAjax" href="../content/ohoopee3.jpg" title="On the Ohoopee as an adult"><img src="../content/ohoopee3.jpg"></a></p>	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
	$(".groupAjax").colorbox({rel:'groupAjax', width: "50%", opacity: 0.65});
</script>
```

When i click on "image 1" colorbox loads the content of ajax.html , then the group of images within ajax.html again need to cycle through in full sized when clicked  however on click of any image it display properly and by clicking next arrow the next images displayed without the width and opacity i specified , On second image there is now right and left arrows so i can't cycle through them further basically i am trying to load colorbox  inside another colorbox.please help me with this.

**Comment by jackmoore** [comment]
http://www.jacklmoore.com/colorbox/faq/#faq-img

**Comment by yasharma** [comment]
As you mentioned within FAQ to specify image height and width, now this is my code
```
<style>
.image-square{ width: 300px; height: 300px; }
</style>
<p>
	<a class="groupAjax" href="../content/ohoopee1.jpg" title="Me and my grandfather on the Ohoopee.">
		<img class="image-square" src="../content/ohoopee1.jpg">
	</a>
</p>
<p>
	<a class="groupAjax" href="../content/ohoopee2.jpg" title="On the Ohoopee as a child">
		<img class="image-square" src="../content/ohoopee2.jpg">
	</a>
</p>
<p>
	<a class="groupAjax" href="../content/ohoopee3.jpg" title="On the Ohoopee as an adult">
		<img class="image-square" src="../content/ohoopee3.jpg">
	</a>
</p>   
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="../jquery.colorbox.js"></script>
<script>
    $(".groupAjax").colorbox({rel:'groupAjax', width: "50%", opacity: 0.65});
</script>
```
i have added class name "image-square" which have width and height of 300px in css. However the problem is still same as i have exampled above

**Comment by jackmoore** [comment]
Sorry, I overlooked before that you were assigning Colorbox to elements that are already displayed in Colorbox.  That's not something that is supported, because that ajax content you loaded no longer exists in the DOM once Colorbox's content changes.  Colorbox can't cycle through those links if they no longer exist in the document.
