### ISSUE TITLE
Content not selectable when initializing per element

### ISSUE THREAD

**Issue by nonumber** [jackmoore/colorbox#776]
Got a weird one.

I have - let's say - 2 links with a class name `my_modal` linking to an internal page.

When I do this, all works fine:
```
$('.my_modal').colorbox();
```
However, when I trigger the colorbox per element, the modals do open as expected, but I cannot select any text inside:
```
$('.my_modal').each(function() {
	$(this).colorbox();
});
```

Any ideas on this?

**Comment by nonumber** [comment]
PS: Only happens with internal content. Iframed content has no issues.

**Comment by jackmoore** [comment]
Those should be equivalent ways of assigning Colorbox.  Since this isn't a problem I've had reported before, I'm afraid you'll have to provide a demo.  Do me a favor and strip out anything unnecessary to reproducing the issue.  My guess is that you'll resolve the issue when creating the minimal reproducible demo, and it won't be something directly related to Colorbox, but post a link to the demo if not and I'll look into it.

**Comment by nonumber** [comment]
Indeed, sorry for wasting your time :)

The issue is caused by an implementation of the jquery.touchSwipe:
```
		$(document).bind('cbox_open', function() {
			$("#colorbox").swipe({
				//Generic swipe handler for all directions
				swipeLeft : function(event, direction, distance, duration, fingerCount) {
					$.colorbox.next();
				},
				swipeRight: function(event, direction, distance, duration, fingerCount) {
					$.colorbox.prev();
				},
				//Default is 75px, set to 0 for demo so any distance triggers swipe
				threshold : 75
			});
		});
```

Will have to figure out how to fix this.

**Comment by nonumber** [comment]
The solution is to add `fallbackToMouseEvents : false`
```
$(document).bind('cbox_open', function() {
			$("#colorbox").swipe({
				//Generic swipe handler for all directions
				swipeLeft : function(event, direction, distance, duration, fingerCount) {
					$.colorbox.next();
				},
				swipeRight: function(event, direction, distance, duration, fingerCount) {
					$.colorbox.prev();
				},
				//Default is 75px, set to 0 for demo so any distance triggers swipe
				threshold : 75,
				fallbackToMouseEvents : false
			});
		});
```

**Comment by jackmoore** [comment]
👍
