### ISSUE TITLE
Hash(#) anchor links in iframes don't work in ios safari

### ISSUE THREAD

**Issue by MeghanaHasabnis** [jackmoore/colorbox#784]
anchor tag in one page(a.php) passes a parameter 'p' to another page (b.php) which causes a list to expand in that page(b.php) using '.collapse('toggle')'.

I need to show this page-b.php in a colorbox iframe which will scroll to view the respective expanded list. 
tried following options which work everywhere except on iPad and iPhones.
    1.  document.getElementById("list").scrollIntoView();
        2.  $("body").animate({ scrollTop: $("#list").offset().top}, 'slow');

Please guide.

**Comment by Codepublish** [comment]
20. jun. 2016 14:34 skrev "MeghanaHasabnis" <notifications@github.com>:
>
> anchor tag in one page(a.php) passes a parameter 'p' to another page
(b.php) which causes a list to expand in that page(b.php) using
'.collapse('toggle')'.
>
> I need to show this page-b.php in a colorbox iframe which will scroll to
view the respective expanded list.

**Comment by Codepublish** [comment]
Sjekk ut CallApp https://goo.gl/s5NNqN & prøv www.callapp.com/d gratis
sosial telefon og nummeropplysning som identifiserer en milliard ukjente
anrop

**Comment by MeghanaHasabnis** [comment]
waiting for a solution!

**Comment by jackmoore** [comment]
Sorry about your problem, but it sounds out of scope of what Colorbox would or should be responsible for.  Colorbox's job is to add the iframe to the document and position it.  I imagine you'd have the same issue regardless of what script or mechanism you used to display the iframe.  Inconsistencies with how browsers handle iframes/scrolling/position are outside the scope of what I want Colorbox to handle.

**Comment by meghana-thinkcreative** [comment]
Okay. Thank you for the reply. :)
