### ISSUE TITLE
Android keyboard overlaying modal window.

### ISSUE THREAD

**Issue by KingWebsites** [jackmoore/colorbox#785]
Hi, I have a form in my modal window with a number of textareas and input fields. My configuration is using 'fixed: true' for my positioning as the content of the modal is normally longer than the screen and 'fixed: false' was giving me some problems.

My issue is that when the Android (Nexus 5X, v6.0) 'soft' keyboard pops up after clicking on an input field it overlays the input field preventing you seeing what you type. In iOS it works fine and the modal window shifts up the exact height as the keyboard. On Android my modal window doesn't change at all. You can't even scroll up to the input field, the bottom of the modal window will go no higher than the bottom of the original viewport.

I was hoping calling a $.colorbox.resize might help to force colorbox to use just the remaining amount of space but this bit of code doesn't seem to be having any effect.

```
onComplete: function() {
  if (isAndroid == true) { // a custom function that DOES work
    setInterval(function(){
      $.colorbox.resize();
    }, 500);
  }
}
```

Does anybody have any advice if they've encountered the same problem? Thanks.

**Comment by KingWebsites** [comment]
Here's the code I created to overcome this issue. It's pretty generic but it seems to work for the majority of users. The logic is that if a form field is clicked in the bottom half of the screen (on Android) it will roll the page up 290px from where it currently is.

```
$('body.device-android').on('click', '#colorbox form input[type=text],#colorbox form textarea, #colorbox form iframe', function() {
  var offset = $(this).offset();
  var scrolledDist = $('#cboxLoadedContent').scrollTop();
  var viewportHeight = $(window).height();
  var yCoordFromBottom = $(window).height() - offset.top;
  if (yCoordFromBottom < viewportHeight / 2) {			
    var scrollHeight = scrolledDist + 290;
    $('#cboxLoadedContent').animate({
      scrollTop: scrollHeight
    }, 400);
  };
});
```

Hope it helps somebody out there.

**Comment by chhuang** [comment]
I'm having the same problem. I wonder if there's a more elegant way of fixing this.

What logic are you using to detect Android devices?

**Comment by KingWebsites** [comment]
I use these to apply body classes (before document ready).

```
if (navigator.userAgent.match(/Android/i)) {
	$('body').addClass('device-android');
}

if (navigator.userAgent.match(/iPhone|iPad|iPod/i)) {
	$('body').addClass('device-ios');
}
```
