### ISSUE TITLE
callbacks not being triggered

### ISSUE THREAD

**Issue by propertunist** [jackmoore/colorbox#788]
i am currently playing with the settings for a colorbox popup that i am adding to my website that is based on the elgg framework (www.elgg.org). elgg uses colorbox by default, so it has some built-in support for calling colorbox and most of the features work fine. however, i am finding that when i have added callout functions to the events that colorbox generates, the functions are never called. for example, i assigned a 'console.log' command to the 'onOpen' event and when i open colorbox, nothing is logged to the browser's console (firefox / linux):
```
'onOpen' => "function() {alert('test'); console.log('open'); }",
```
does anyone know why? or have any tips on how to debug this? thanks

**Comment by jackmoore** [comment]
> `'onOpen' => "function() {alert('test'); console.log('open'); }",`

I don't know what I'm looking at here, what language is this?  It looks like you are assigning a string to `onOpen` instead of a function.  Colorbox takes a settings object, and the callback properties expect a value that is a function.

**Comment by propertunist** [comment]
oh ok, yes. this is PHP - it's just an assignment of the callback function to a value that gets output as a JSON attached to an HTML element. to make it clearer, the callback function would be written in javascript as:
```
onOpen: function() {alert('test'); console.log('open'); }
```
the full PHP call within elgg is:
```
$img = elgg_view_entity_icon($image, 'large', array(
	'link_class' => 'elgg-lightbox',
	'href' => 'ajax/view/ureka/image_popup?guid=' . $image->guid,
	'data-colorbox-opts' => json_encode([
		'height' => '96%',
		'width' => '96%',
		'fixed' => true,
		'className' => 'imagebox' . $image->guid,
	  'onOpen' => "function() {alert('test'); console.log('open'); };",
	]),
));
```

**Comment by propertunist** [comment]
oh it appears i have some useful advice via the elgg core team here: https://elgg.org/discussion/view/2518007/colorbox-callback-functions-are-not-being-triggered-here-anyone-know-why

**Comment by jackmoore** [comment]
👍 Sounds like they pointed you in the right direction.
