### ISSUE TITLE
CORS if image URL has no file extension

### ISSUE THREAD

**Issue by walknwind** [jackmoore/colorbox#790]
Hey hey! <3 this plugin, but just stumbled-upon my 1st issue using it. My images are served via an AWS cloudfront CDN (so not from the same source as the webpage). I'm finding that if an image URL is something like `https://...cloudfront.../image_file.png`, all's well.

But if an image URL is something like `https://...cloudfront.../image_file`, I get a CORS error and the content doesn't load in the colorbox modal. I'm still trying to understand who is getting tripped up by this (might not be colorbox at all)...

**Comment by jackmoore** [comment]
Colorbox is failing to recognize that the address should be treated as an image, and defaults to trying making an ajax request for content.  There isn't an efficient way to Colorbox to determine the mime-type of the content being requested, so it uses a regex to look for known image file extensions instead.  The regex is customizable, but you can also explicitly tell Colorbox that the url should be treated as an image source using the [`photo` property](http://www.jacklmoore.com/colorbox/#setting-photo).

For example:
```
<a class='isPhoto' href='https://...cloudfront.../image_file'>image</a>
<a class='isAjax' href='https://...cloudfront.../html_file'>html snippet</a>
<script>
  $('a.isPhoto').colorbox({photo: true});
  $('a.isAjax').colorbox();
</script>
```
