### ISSUE TITLE
Trying to use multiple colorbox ajax links on one page

### ISSUE THREAD

**Issue by roybman** [jackmoore/colorbox#797]
I have a page where I'm showing multiple content boxes.  Each content box contains an href link with a url parameter, i.e. "<a href='/getcontentdata?id=27' class='options'></a>"  The id would be different i each link.  There could an indefinite number of these on a page.  In my jquery, I have: 
	$(".options").colorbox({
    });
The issue I'm encountering seems to be that colorbox is trying to look at the href links in each instance of the options class, always starting with the one I click on.  Viewing it in Firebug, it appears to get the correct link but then tries to cycle to the next instance of the options class without firing off the ajax call, at which point it fails.  On the second hit of $(".options").colorbox({ });, the firebug error states "TypeError: $(...).colorbox is not a function".  
I know this can be done using the inline method, as I'm already doing it that way on another page, but I wanted to do it via ajax instead to handle the possibility of someone having multiple tabs open to my site.  Since I did not define "REL", I was expecting colorbox to fire off ajax to the link that was clicked.  Is it possible to do what I'm trying using Colorbox?  If so, what am I doing wrong?  Any input is greatly appreciated.

**Comment by jackmoore** [comment]
Sorry, I'm not able to follow your description.  Could you post a simplified demo of what you are doing to jsfiddle or something?  If I could see what you are actually doing that would be a big help.

**Comment by roybman** [comment]
Jack, thanks very much.  On one hand, I had an issue I just found while putting together a jsfiddle for this.  However, I am still encountering a strange issue.  I think I need a little time to look at what is happening before I pursue this with you further.  For now I will close this and will come back when I can better present the issue.  Thanks.
