### ISSUE TITLE
jQuery live() is deprecated

### ISSUE THREAD

**Issue by tribulant** [jackmoore/colorbox#798]
I've seen jQuery live() failing in some instances with newer jQuery versions.

Since jQuery live() is deprecated and has been since jQuery 1.7, is it possible to switch it out to on() to prevent conflicts/Javascript errors?

http://api.jquery.com/live/

**Comment by jackmoore** [comment]
Colorbox does use on().  If that's no available (if you are using a very old version of jQuery), it falls back to using live().  It's just there for backwards compatibility, removing it just breaks automated updates for those legacy users for no reason.

Here is the context in which live() is used, you can see on() is checked for first:

```
if ($.isFunction($.fn.on)) {
	// For jQuery 1.7+
	$(document).on('click.'+prefix, '.'+boxElement, clickHandler);
} else {
	// For jQuery 1.3.x -> 1.6.x
	// This code is never reached in jQuery 1.9, so do not contact me about 'live' being removed.
	// This is not here for jQuery 1.9, it's here for legacy users.
	$('.'+boxElement).live('click.'+prefix, clickHandler);
}
```

**Comment by tribulant** [comment]
Ah, my apologies, I see now.

**Comment by jackmoore** [comment]
No worries, thanks for looking out.
