### ISSUE TITLE
Colorbox - how to pass several parameters

### ISSUE THREAD

**Issue by cr0pster** [jackmoore/colorbox#804]
I use colorbox directly after loading a page under certain conditions. I displays a html text like this:
$.colorbox({html:"Vielen Dank für Ihre Registrierung!...")}
However, the text above is abridged; in reality it is much longer which results in a box as wide as my monitor. I would like to add $.colorbox({inline:true, width:"50%"}) but I'm unable to do so. Any attempt to mix these parameters fails, i.e.:
$.colorbox({inline:true, width:"50%", html:"Vielen Dank für Ihre Registrierung!...")} or
$.colorbox({
inline:true,
width:"50%",
html:"Vielen Dank für Ihre Registrierung!...
}) or
$.colorbox({inline:true, width:"50%"});
$.colorbox({html:"Vielen Dank für Ihre Registrierung!...")}
How can I achieve this? Furthermore, I'd like to trigger/load an external website automatically in the process (like a window.open command; in the background, the user shouldn't notice it for it triggers a process needed for the registration to complete)

Thanks in advance

**Comment by jackmoore** [comment]
You'd have to pick either 'html' or 'inline', they are mutually exclusive.

This should work:
```
$.colorbox({
  html:"Vielen Dank für Ihre Registrierung!...",
  width: "50%",
)}
```

> How can I achieve this? Furthermore, I'd like to trigger/load an external website automatically in the process (like a window.open command; in the background, the user shouldn't notice it for it triggers a process needed for the registration to complete)

I'm not sure exactly what you are asking about, but it sounds like you would want to use the onComplete callback to fire off some function of your own design.  For example:

```
$.colorbox({
  html:"Vielen Dank für Ihre Registrierung!...",
  width: "50%",
  onComplete: function(){
    // do something like window.open
  }
)}
```

**Comment by cr0pster** [comment]
Thank you, this worked!

 

 

Mit herzlichen Grüßen,

 

Michael Podolsky



Description: 2011-07-21_Logo für Outlook

www.podcomm.net <http://www.podcomm.net/> 

Tel.    (030) 751 64 88

Mobil 0176 576 12 598
