### ISSUE TITLE
Event on next/previous actions

### ISSUE THREAD

**Issue by remayex** [jackmoore/colorbox#805]
Is there any way to bind a function to a next or previous action ?
Thanks.

**Comment by jackmoore** [comment]
Not really.  The onComplete callback will fire each time, if that is adequate.  As a workaround you can overwrite the public methods.  Here's an example:

```js
// first save a reference to the original function
var next = $.colorbox.next;

// overwrite
$.colorbox.next = function(){
  console.log('next!');
  next();
};
```

**Comment by remayex** [comment]
Thanks for your answer.
I thought the "cbox_complete" event was fired only once when the colorbox open for the first time.
As you pointed it is indeed fired every time a new content loads, so it's almost equivalent to next or previous action if you don't care if it is next or previous content that is loaded.
That is my use case, it worked for me.
Thanks !
