### ISSUE TITLE
iframe allowFullScreen

### ISSUE THREAD

**Issue by tklawsuc** [jackmoore/colorbox#816]
using 1.6.4, iframe does not allow for fullscreen view. To fix the issue I added the setAttribute methods as follows:
jquery.colorbox.js
`iframe.allowFullScreen = true;
iframe.setAttribute("allowFullScreen", true);`
jquery.colorbox-min.js
`i.allowFullScreen=!0,i.setAttribute("allowFullScreen", !0),` 

Tested before and after in firefox 48.0.2 and chrome 49.0.2623.112

**Comment by matrefeytontias** [comment]
As of 1.6.2, the attribute has been renamed `allowFullscreen` as opposed to `allowFullScreen`.

**Comment by jackmoore** [comment]
@tklawsuc Can you explain to me how to reproduce the problem you were experiencing? I need to be able to verify that adding setAttribute resolves some issue over directly access of the attribute.  Thanks.

**Comment by jackmoore** [comment]
@matrefeytontias is correct, you just need to use version 1.6.2 or newer.  You say you are using 1.6.4, but the code you posted has to have been from something older than 1.6.2.  Changing the property name from 'allowFullScreen' to 'allowFullscreen' did fix the issue you are describing.
