### ISSUE TITLE
Color box work on mobiles or tablets

### ISSUE THREAD

**Issue by lse123** [jackmoore/colorbox#818]
Color box work on mobiles or tablets? 
Sthg error in my code and not open the slideshow on Android mobile devices... any hint? Only Android tested till now...,

**Comment by Globulopolis** [comment]
@lse123 could you provide some of you code which you use to init colorbox?

PS! And answering on you question - yes, w/o any problem.

**Comment by lse123** [comment]
seems and in desktop when resize to small size the browser window does not work....i have this:
well
```
	$(document).ready(function(){
		if ($( window ).width() > 1200) {
			$(".group4").colorbox({rel:'group4', slideshow:true, width:"50%", height:"60%"});		
		} else if ($( window ).width() > 801) {
			$(".group4").colorbox({rel:'group4', slideshow:true, width:"70%", height:"60%"});		
		} else {
			$(".group4").colorbox({rel:'group4', slideshow:true, width:"90%", height:"90%"});
		}
	});	
```

**Comment by lse123** [comment]
http://followthesuncyprus.com/gallery.php

**Comment by Globulopolis** [comment]
@lse123 it's working on desktop Firefox, Chrome and Chrome mobile(tested on xiaomi mi4c miui 8). But when I open your site in resized window(e.g. 600x450px) when I see that the `<div class="article">` blocked by the next `<div class="row">`. So it's not a problem with colorbox, with is something wrong with you html-markup.

**Comment by lse123** [comment]
removed a div tag - fixed and in firefox mobile 
thks a lot
