### ISSUE TITLE
jQuery Colorbox log messages

### ISSUE THREAD

**Issue by mskogly** [jackmoore/colorbox#826]
I'm trying to figure out how to turn off the console.log, but can't find any settings or documentation.
Inspect and view console on this: https://p3.no/dokumentar/gal-av-kjaerlighet.

Of course, colorbox is included via a wordpress plugin, so I will also look for answers on http://www.techotronic.de/plugins/jquery-colorbox/

**Comment by jackmoore** [comment]
This is something added by the Wordpress plugin that you are using that incorporates Colorbox.  You'll have to ask the Wordpress plugin author about it.
