### ISSUE TITLE
How to load HTML async!?

### ISSUE THREAD

**Issue by mathishuettl** [jackmoore/colorbox#829]
Hello,

I want to load content coming from an api to the colorbox. My example below is working, but it's not how i want. The problem now is, that as soon as i click an item (or click next / prev) it begins to load and continue when everything is done. But that's to slow for me. it would be perfect if the data gets loaded async, but i don't know how....

can you help me plase?

```
$(".item").colorbox({
        rel: "g-1",
        html: function() {
            var post_id = $(this).attr("data-post");
            var html = "";

            $.ajax({
                url: "/api/post/" + post_id,
                type: "GET",
                async: false,
                success: function(result) {
                    html = result.mediaUrl;
                }
            });

            return html;
        }
    });
```

**Comment by jackmoore** [comment]
Sorry, Colorbox doesn't preload ajax content.  I don't really see an easy workaround that is going to work well with grouped content.
