### ISSUE TITLE
onComplete doesn't support iframes

### ISSUE THREAD

**Issue by dehghani-mehdi** [jackmoore/colorbox#831]
Hey,

When using `iframe`, I expected `onComplete ` fire after `iframe` loaded completely, but it doesn't and fire before that. 

I'm using latest version of `Colorbox` btw.

Thanks.

**Comment by jackmoore** [comment]
Try setting the fastIframe option to false: http://www.jacklmoore.com/colorbox/#setting-fastiframe

Example:
```
$('.example').colorbox({iframe: true, fastIframe: false});
```

**Comment by dehghani-mehdi** [comment]
Awesome man, thanks!
