### ISSUE TITLE
Adding Colorbox to my ReactJS application creates “jQuery is not defined”

### ISSUE THREAD

**Issue by ktrzos** [jackmoore/colorbox#836]
I'm trying to add Colorbox library to my project created with create-react-app. I've installed jquery-colorbox package via npm and added imports in one of my *.js files.

The whole problem description is here:
https://stackoverflow.com/questions/44850631/adding-colorbox-to-my-reactjs-application-creates-jquery-is-not-defined

**Comment by jackmoore** [comment]
Sorry, I do not know, but this does not seem specific to Colorbox.  I'm going to close this since I expect you could replace Colorbox with any other jQuery plugin and be in the same situation.

**Comment by ktrzos** [comment]
All right. Worth trying ;). Thanks for the response.

**Comment by ktrzos** [comment]
If anyone would ask, the solution is on the Stackoverflow in here:
https://stackoverflow.com/questions/44850631/adding-colorbox-to-my-reactjs-application-creates-jquery-is-not-defined
:)
