### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by CarrotCake63** [jackmoore/colorbox#842]
Will there be a version that works with bootstrap - this seems to cause various issues in the colorbox lightbox which I am unable to resolve.

**Comment by donaldboulton** [comment]
Its not conflicting with bootstrap in its stock css. I have been using colorbox since bootstrap 2, 3+ and now with 4 beta 3 and no issues at all

**Comment by jackmoore** [comment]
@donaldboulton Thanks, I had not tried to verify the issue myself but I would not expect CSS conflicts unless it was adding something unconventional style to element selectors (e.g. `div { float: left; }`.  Colorbox's example stylesheet doesn't attempt to reset every possible style to prevent conflicts, but that has very rarely been an issue that I've seen.
