### ISSUE TITLE
is there a way to use arrow function as callback?

### ISSUE THREAD

**Issue by chantisnake** [jackmoore/colorbox#849]
here is my rather simple code:
```js
  photosView.find('.photo').colorbox({
    rel: 'photo', transition: 'elastic', height: '75%',
    title: function () {return $(this).data("description")}
  })
```

For consistency and conciseness reason, I want to change the `title` callback to arrow function, but because of the scope handling of arrow function, I cannot use `$(this)` anymore. 

Is there a way to fix this?

Thanks

**Comment by jackmoore** [comment]
For arrow functions the value of `this` is set by the context in which the arrow function was defined, and cannot be changed.  So using `this` is off the table.  However, Colorbox passes a data object as an argument to the function.  This data object has a lot of information in it beyond just the DOM node, so to access just the DOM node use the `el` property of the object.  Here's an example:

```
  photosView.find('.photo').colorbox({
    rel: 'photo', transition: 'elastic', height: '75%',
    title: (o)=> $(o.el).data("description"),
  })
```
