### ISSUE TITLE
How to set and get options after initinialization?

### ISSUE THREAD

**Issue by Aybee** [jackmoore/colorbox#853]
How do we have to change options for already initialized colorboxes.

I have some links which I've set the colorbox on.
```js
$('a[data-lightbox]').map(function() {
  $(this).colorbox({
    // Put custom options here
    rel: $(this).attr('data-lightbox'),
    maxWidth: '95%',
    maxHeight: '95%'
  });
});
```
Now some of those links should get other options. I like to reset, change or add some options for those special links. How should this be done? Is there a setter and getter?

**Comment by jackmoore** [comment]
Just assign Colorbox to your element again with your new options. It applies the new options on top of the old, so if your new options contain properties that are incompatible with a previous option, you'll want to also set the previous option to false.

For example, this will update the maxWidth property while retaining the other options:
```
$('a[data-lightbox]').map(function() {
  $(this).colorbox({
    // Put custom options here
    rel: $(this).attr('data-lightbox'),
    maxWidth: '95%',
    maxHeight: '95%'
  });
});
$('a[data-lightbox]').colorbox({maxWidth: '50%'});
```

**Comment by jackmoore** [comment]
If for some reason you need to view what options you previously applied to a specific element, you can view them by using `$(element).data('colorbox')`.

Example:
```
$('a[data-lightbox]').eq(2).data('colorbox');
```

**Comment by Aybee** [comment]
Ah, very good. Thank you very much.
