### ISSUE TITLE
Html5 video caption don't sink after controls disappear

### ISSUE THREAD

**Issue by ninjarails** [jackmoore/colorbox#861]
This issue only happens on Chrome.
Video caption positioned over the controls when controls is shown. That's good. But when the controls disappear, it should be placed lower than it was with controls. But it persists the same position.
![screen shot 2018-07-04 at 10 57 43 am](https://user-images.githubusercontent.com/20705027/42288709-1d3a6fc4-7f79-11e8-98f0-d0c9837d2398.png)
![screen shot 2018-07-04 at 10 57 50 am](https://user-images.githubusercontent.com/20705027/42288710-1d7eb1e8-7f79-11e8-9f12-a1dabdce37dd.png)

**Comment by jackmoore** [comment]
Sorry for your troubles, but I doubt there is anything about this that is specific to Colorbox or that Colorbox could do to resolve.
