### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [jackmoore/colorbox#863]
Hi @jackmoore . I'm a graphic designer and an open source enthusiast. I would like to contribute to your project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard. 
Mirza zulfan.

**Comment by jackmoore** [comment]
Hi Mirza, thank you for your offer. It's tempting but I've thought about this and decided that I wouldn't feel good about it. I'm a designer too and I think I would feel guilty about someone else making the logo for my project. I think I'm most content to let it continue on as is. I hope you understand and thank you again for the generous offer.
