### ISSUE TITLE
Can't submit form on iPhone

### ISSUE THREAD

**Issue by Ange7** [jackmoore/colorbox#870]
hi,
I'm using colorbox with iframe : 

```
$('.colorbox').colorbox({
        iframe:true,
        innerWidth:500,
        innerHeight:350
    });
```

with data-url attribute on <a class="colorbox"></a>

It's working perfectly on desktop, but on my iPhone (safari) when i submit form in my target url the page is reload

is it a problem with colorbox ? (sandbox attributes?)
thank you

**Comment by jackmoore** [comment]
Sorry, I doubt this has anything to do with Colorbox. Make sure you have your dubugger on and that it breaks on errors. That should allow you to catch and see the error before the default behavior allows the page to redirect.
