### ISSUE TITLE
Colorbox Resizing Parent's Width

### ISSUE THREAD

**Issue by ecreamer** [jackmoore/colorbox#903]
Hi,

We have used Colorbox many times and never seen this issue before. When the Colorbox opens, the width of the parent's content is being resized.

Without Colorbox Open:
![image](https://user-images.githubusercontent.com/86733505/151421632-52970c5b-e726-443d-bd5a-d92d70e1e7d1.png)

With Colorbox Open:
![image](https://user-images.githubusercontent.com/86733505/151421710-cbd488f9-ed7a-4564-a314-d8a179d68799.png)

Please take note of the right side of the screen. Either the width of the content is shrinking when the Colorbox is opened, or an excessive amount of right margin/padding is being added. Any suggestions on fixing this?

**Comment by jackmoore** [comment]
What options are you passing Colorbox? Have you tried using the maxWidth setting? This isn't enough info to diagnose your issue with any confidence.

**Comment by ecreamer** [comment]
The Colorbox initializes with the following:

if(windowwidth > 1000 && windowheight > 1000)
	$.colorbox({ href: href1, height:'70%', width:'90%' });
else
	$.colorbox({ href: href1, maxHeight:'400px', height:'90%', width:'90%' });

The problem is fixed if I supply a fixed width on my content, but that is not feasible for what we are doing. The Colorbox also stays inside of the window, it is only shrinking the content of the parent.

**Comment by jackmoore** [comment]
> The Colorbox also stays inside of the window, it is only shrinking the content of the parent.

This shouldn't happen. I feel like something else is going on that would not be possible to diagnose without seeing a demo that could be inspected.

**Comment by ecreamer** [comment]
There was a weird style on the parent that was causing this issue.
